1. What is a Python library? Why do we use Python libraries?

A Python library is a collection of pre-written code modules that provide reusable functions, classes, and constants to facilitate specific tasks. These libraries extend the functionality of Python by offering solutions to common programming challenges across various domains.

      We use Python libraries for several reasons:
      
Efficiency:
Libraries provide ready-made solutions, allowing developers to save time and effort by avoiding the need to write code from scratch for common tasks.

Code Reusability:
Python libraries encapsulate reusable code components, enabling developers to leverage existing functionality in multiple projects without duplicating efforts.

Domain-specific Functionality:
Libraries cater to specific domains such as web development, data analysis, machine learning, natural language processing, etc., offering tools and algorithms tailored to the needs of those fields.

Performance Optimization: 
Many Python libraries include optimized implementations of algorithms and data structures, enhancing the performance of applications.

Community Support: 
Python libraries often have active communities of developers who contribute to their improvement and maintenance. This community support ensures that libraries are continuously updated, reliable, and compatible with the latest Python versions.

Interoperability: 
Python libraries can integrate seamlessly with other libraries and frameworks, enabling developers to combine functionalities from multiple sources to build comprehensive solutions


2. What is the difference between Numpy array and List?

NumPy arrays and Python lists are both data structures used for storing collections of elements, but they have several key differences:

Memory Efficiency:
NumPy arrays are more memory efficient compared to lists. NumPy arrays are stored in contiguous memory, meaning all elements are stored next to each other, while lists store references to objects, leading to overhead in memory usage.

Performance:
NumPy arrays offer better performance for numerical operations and computations compared to lists. NumPy's operations are implemented in C, which makes them much faster than the equivalent operations on Python lists, especially for large datasets.

Type Homogeneity:
NumPy arrays are homogeneous, meaning all elements in an array must have the same data type (e.g., integers, floats). This allows for more efficient storage and operations. In contrast, Python lists can contain elements of different data types.

Functionality:
NumPy arrays offer a wide range of mathematical functions and operations for numerical computing, such as element-wise operations, linear algebra operations, statistical functions, and more. Lists, on the other hand, provide more general-purpose functionality but lack specialized numerical computing capabilities.

Syntax and Usage:
Accessing elements and performing operations on NumPy arrays is often more concise and intuitive compared to lists, especially when dealing with multidimensional arrays or numerical computations.

Mutability:
Both NumPy arrays and Python lists are mutable, meaning their elements can be modified after creation. However, the methods for modifying elements may differ slightly between the two data structures.

In [8]:
#3. Find the shape, size and dimension of the following array ?
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8] , [9,10,11,12]])
arr_shape = np.shape(arr)
arr_size = np.size(arr)
arr_dimension = arr.ndim

print(f" this array shape is : {arr_shape}")
print(f" this array size is : {arr_size}")
print(f" this array dimension is : {arr_dimension}")

 this array shape is : (3, 4)
 this array size is : 12
 this array dimension is : 2


In [10]:
#4. Write python code to access the first row of the following array?
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8] , [9,10,11,12]])
access_first_row = arr[0]
print(f"The first row is : {access_first_row}")

The first row is : [1 2 3 4]


In [12]:
#5. How do you access the element at the third row and fourth column from the given numpy array?
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8] , [9,10,11,12]])
element = arr[2,3]
print(f"The element at the third row and fourth column is: {element}")

The element at the third row and fourth column is: 12


In [13]:
#6. Write code to extract all odd-indexed elements from the given numpy array?
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8] , [9,10,11,12]])
odd_indexed_element = arr[arr % 2 == 1]
print(f"Odd-indexed elements: {odd_indexed_element}")

Odd-indexed elements: [ 1  3  5  7  9 11]


In [27]:
#7.How can you generate a random 3x3 matrix with values between 0 and 1?
import numpy as np 
import random
random_matrix = np.random.random((3,3))
print(f"ramdom matrix is : {random_matrix}")

ramdom matrix is : [[0.86130334 0.46568563 0.14741519]
 [0.27429854 0.86432239 0.73691291]
 [0.93617987 0.99220498 0.82983459]]


#8. Describe the difference between np.random.rand and np.random.randn?

The NumPy library in Python provides two functions for generating random numbers: np.random.rand and np.random.randn. Although they may seem similar, they have distinct differences in terms of the distribution of the generated random numbers:

np.random.rand:
np.random.rand generates random numbers from a uniform distribution over the range [0, 1).
It takes in dimensions as arguments and returns an array of random numbers with those dimensions.
Each element in the generated array is sampled independently and uniformly from the interval [0, 1).

np.random.randn:
np.random.randn generates random numbers from a standard normal distribution (mean=0, variance=1).
It also takes in dimensions as arguments and returns an array of random numbers with those dimensions.
The random numbers generated by np.random.randn follow a Gaussian (normal) distribution, centered around 0 with a standard deviation of 1.
The distribution of numbers generated by np.random.randn is not uniform; instead, it follows the bell-shaped curve characteristic of the normal distribution.

In [33]:
#9. Write code to increase the dimension of the following array?
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8] , [9,10,11,12]])
expand_dimes = np.expand_dims(arr , axis = 0)
print(expand_dimes)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [38]:
#10. How to transpose the following array in NumPy?
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8] , [9,10,11,12]])
transpose_array = np.transpose(arr)
print(transpose_array)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [5]:
#11. Consider the following matrix:
import numpy as np 
matrix_A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
matrix_B = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
#index wise multiplication 
result = np.multiply(matrix_A , matrix_B)
print("index wise multiplication :")
print(result)
#2.Matix multiplication
matrix_mul = matrix_A @  matrix_B #matrix multiplication is not posible because 3 rows  and 4 columns 
print("matrix multiplication :")
print(matrix_mul)

index wise multiplication :
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [6]:
#Subtract matix  B from A 
matrix_sub = matrix_B - matrix_A 
print("matrix subtract : ")
print(matrix_sub)

matrix subtract : 
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [7]:
# Add both the matrix 
matrix_add = matrix_A + matrix_B
print("add both the matrix :")
print(matrix_add)

add both the matrix :
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [8]:
#Divide Matrix B by A
matrix_div = matrix_B / matrix_A 
print('Divide Matrix B by A :')
print(matrix_div)

Divide Matrix B by A :
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
#12.Which function in Numpy can be used to swap the byte order of an array?
'''In NumPy, you can use the byteswap() function to swap the byte order of an array. 
This function swaps the byte order of the elements in the array. 
You can specify the byte order you want using the byteorder parameter.'''
import numpy as np

arr = np.array([1, 2, 3, 4], dtype =  np.int32)
print("Original array:")
print(arr)

# Swap byte order
arr_swapped = arr.byteswap()
print("\nArray with byte order swapped:")
print(arr_swapped)


Original array:
[1 2 3 4]

Array with byte order swapped:
[16777216 33554432 50331648 67108864]


In [13]:
#13. What is the significance of the np.linalg.inv function?

'''The np.linalg.inv function in NumPy is used to compute the multiplicative inverse of a matrix. 
In linear algebra, the multiplicative inverse of a square matrix A is another matrix, denoted as A⁻¹,
such that the product of A and A⁻¹ equals the identity matrix.'''

'The np.linalg.inv function in NumPy is used to compute the multiplicative inverse of a matrix. \nIn linear algebra, the multiplicative inverse of a square matrix A is another matrix, denoted as A⁻¹,\nsuch that the product of A and A⁻¹ equals the identity matrix.'

In [17]:
#14. What does the np.reshape function do, and how is it used?

'''The np.reshape function in NumPy is used to change the shape (dimensions) of an array without changing its data.
It allows you to reorganize the elements of an array into a new shape while preserving the same total number of elements.'''


#example 

import numpy as np 
arr =  np.arange(12)
print('Orginal array')
print(arr)

reshape_arr = np.reshape(arr,(3,4))
print("reshape to 3*4 array:")
print(reshape_arr)

reshape_array = np.reshape(arr,(2,6))
print("Reshape to 2*6 array:")
print(reshape_array)

Orginal array
[ 0  1  2  3  4  5  6  7  8  9 10 11]
reshape to 3*4 array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshape to 2*6 array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [19]:
#15. What is broadcasting in Numpy?

'''When performing operations on arrays, NumPy compares their shapes element-wise.
It starts from the trailing (rightmost) dimension and works its way left.
Two dimensions are compatible when they are equal or when one of them is 1.
If these conditions are not met, a ValueError is thrown, indicating incompatible shapes.
Input arrays do not need to have the same number of dimensions.
The resulting array will have the same number of dimensions as the input array with the greatest number of dimensions, where the size of each dimension is the largest size among the input arrays.
Missing dimensions are assumed to have size one.'''

import numpy as np 
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],])
result = a*b
print(result)

[1 4 9]
